name: CI/CD pipeline
# Trigger for running job
on:
  # Run jobs when pushing code to the branch 'main'
  push:
    branches: [ main ]
jobs:
  # Job 1: Build Docker image
  build:
    # Set up environment
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout git repository
      - name: Checkout
        uses: actions/checkout@v2
      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Step 4: Cache Docker image layers
      - name: Cache Docker Image Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
      # Step 5: Build and push Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testcicd:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
  # Job 2: Deploy to Ubuntu server
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Runs after the 'build' job has completed
    steps:
      # Step 1: Connect via SSH to the server and pull image from Docker Hub
      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/testcicd:latest
            # Stop and remove the old container, if it exists
            docker stop testcicd || true
            docker rm testcicd || true
            # Run the new container with environment variables
            docker run -d -p 80:3000 --name testcicd \
              -e PORT=${{ secrets.PORT }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/testcicd:latest
